### ISSUE TITLE
ci/install_docker.ps1 breaks PATH variable

### ISSUE THREAD

**Issue by Attil** [codilime/contrail-windows-docker#28]
Hi.

Thanks for the plugin!

When installing docker using `ci/install_docker.ps1`, the script breaks PATH environmental variable. The result is garbage in `$env:PATH`. I think `[system.String]::Join(";", $p)` should instead be `$p = [system.String]::Join(";", $p)`

**Comment by m-kostrzewa** [comment]
Works for me 💃

**Comment by mmasztalerczuk** [comment]
Pull request https://github.com/codilime/contrail-windows-docker/pull/29
